### ISSUE TITLE
how to get MongoDB uri

### ISSUE THREAD

**Issue by asher23455** [RabbitHouseCorp/ChinoKafuu#123]
can i know how to get it cause it is not working for me

**Comment by IamTheRealSami** [comment]
[Click here](https://cloud.mongodb.com) Sign in, create a db cluster. Click on Connect and you should see connect with URI or smth like that

**Comment by asher23455** [comment]
![image](https://user-images.githubusercontent.com/69888898/104700602-6fc78b00-573a-11eb-80d3-499d4548e26d.png)
can i know what to do now

**Comment by asher23455** [comment]
> [Click here](https://cloud.mongodb.com) Sign in, create a db cluster. Click on Connect and you should see connect with URI or smth like that

help pls

**Comment by TheEdaL06** [comment]
Good, I will help you to connect mongodb to the bot, for that it is very easy if you follow my steps:

> 1.- Create an account in [MongoDB](https://account.mongodb.com/account/register)
> 2.- Login in the account and create a Cluster
> 3.- Create a user and password for the Cluster
> 3.- Wait for it to be created and then click on **CONNECT**
> 4.- Go to "Connect your application" and copy what you see
> 5.- Modify the data: 
> `<username>` - Your user
> `<password>` - Your Password
> `<dbname>` - Your Database Name

Here is a video in case you did not understand: [Video Support](https://www.youtube.com/watch?v=nwgQzuRRgec&ab_channel=MarinaKim)

![image](https://user-images.githubusercontent.com/31509039/107279633-9639c700-6a57-11eb-9acf-11a5f9f8204f.png)
![image](https://user-images.githubusercontent.com/31509039/107280002-0fd1b500-6a58-11eb-989d-0ffd3097e643.png)

I hope I have helped you!

**Comment by NavyCake** [comment]
Well it's a good solution, it will be closed.
